name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensure all tags are fetched

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Use the appropriate .NET version

    - name: Generate version based on timestamp
      run: echo "version=1.0.$(date +%s)" >> $GITHUB_ENV

    - name: Debug generated version
      run: echo "Generated version:${{ env.version }}"

    - name: Update version in .csproj
      run: |
        version=${{ env.version }}
        sed -i 's/<Version>.*<\/Version>/<Version>'$version'<\/Version>/' MongoNet/MongoNet/MongoNet.csproj

    - name: Restore dependencies
      run: dotnet restore MongoNet/MongoNet.sln

    - name: Build
      run: dotnet build MongoNet/MongoNet.sln --configuration Release --no-restore

    - name: Pack
      run: dotnet pack MongoNet/MongoNet.sln --configuration Release --no-restore --output ./artifacts
    - name: Publish package
      env:
        MY_PAT: ${{ secrets.MONGONET_PUBLISH  }}
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.MONGONET_PUBLISH  }} -s https://nuget.pkg.github.com/nawarajkhadka/index.json
      
      
