name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Use the appropriate .NET version
        
    - name: Get latest tag
      id: get_latest_tag
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

    - name: Increment version
      id: increment_version
      run: |
        latest_tag=${{ steps.get_latest_tag.outputs.tag }}
        version=$(echo $latest_tag | awk -F. '{print $1"."$2"."$3+1}')
        echo "::set-output name=version::$version"

    - name: Update version in .csproj
      run: |
        version=${{ steps.increment_version.outputs.version }}
        sed -i 's/<Version>.*<\/Version>/<Version>'$version'<\/Version>/' MongoNet/MongoNet/MongoNet.csproj
        
    - name: Restore dependencies
      run: dotnet restore MongoNet/MongoNet.sln

    - name: Build
      run: dotnet build MongoNet/MongoNet.sln --configuration Release --no-restore

    - name: Pack
      run: dotnet pack MongoNet/MongoNet.sln --configuration Release --no-restore --output ./artifacts

    - name: Publish package
      env:
        MY_PAT: ${{ secrets.MONGONET_PUBLISH  }}
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.MONGONET_PUBLISH  }} -s https://nuget.pkg.github.com/nawarajkhadka/index.json
      
      
