name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensure all tags are fetched

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Use the appropriate .NET version

    - name: Get latest tag
      id: get_latest_tag
      run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Debug latest tag
      run: echo "Latest tag:${{ env.tag }}"

    - name: Increment version
      id: increment_version
      run: |
        latest_tag=${{ env.tag }}
        if [ -z "$latest_tag" ]; then
          version="1.0.0"
        else
          version=$(echo $latest_tag | awk -F. '{print $1"."$2"."$3+1}')
        fi
        echo "version=$version" >> $GITHUB_ENV

    - name: Debug incremented version
      run: echo "Incremented version:${{ env.version }}"

    - name: Update version in .csproj
      run: |
        version=${{ env.version }}
        sed -i 's/<Version>.*<\/Version>/<Version>'$version'<\/Version>/' MongoNet/MongoNet/MongoNet.csproj

    - name: Restore dependencies
      run: dotnet restore MongoNet/MongoNet.sln

    - name: Build
      run: dotnet build MongoNet/MongoNet.sln --configuration Release --no-restore

    - name: Pack
      run: dotnet pack MongoNet/MongoNet.sln --configuration Release --no-restore --output ./artifacts
    - name: Publish package
      env:
        MY_PAT: ${{ secrets.MONGONET_PUBLISH  }}
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.MONGONET_PUBLISH  }} -s https://nuget.pkg.github.com/nawarajkhadka/index.json
      
      
