name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Use the appropriate .NET version

    - name: Restore dependencies
      run: dotnet restore MongoNet/MongoNet.sln

    - name: Build
      run: dotnet build MongoNet/MongoNet.sln --configuration Release --no-restore

    - name: Pack
      run: dotnet pack MongoNet/MongoNet.sln --configuration Release --no-restore --output ./artifacts

    - name: Publish package
      env:
        GITHUB_TOKEN: ${{ secrets.MONGONET_PUBLISH }}
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.MONGONET_PUBLISH }} -s https://nuget.pkg.github.com/nawarajkhadka/index.json
      
      
